apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "fleet-onboard-app.fullname" . }}
  labels:
    {{- include "fleet-onboard-app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
    {{- include "fleet-onboard-app.selectorLabels" . | nindent 6 }}
{{ toYaml .Values.podDisruptionBudget | indent 2 }}