apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "fleet-onboard-app.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  data:
  - remoteRef:
      key: {{ .Release.Namespace }}/compass-iot/apikey
    secretKey: COMPASS_API_KEY
  - remoteRef:
      key: {{ .Release.Namespace }}/compass/presharedkey
    secretKey: COMPASS_PRE_SHARED_KEY
  - remoteRef:
      key: {{ .Release.Namespace }}/fleet_onboard/paymaster_url
    secretKey: PAYMASTER_URL
  - remoteRef:
      key: {{ .Release.Namespace }}/fleet_onboard/rpc_url
    secretKey: RPC_URL
  - remoteRef:
      key: {{ .Release.Namespace }}/fleet_onboard/bundler_url
    secretKey: BUNDLER_URL

  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager-secret-store
  target:
    name: {{ include "fleet-onboard-app.fullname" . }}-secret
    template:
      metadata: {}
