ENVIRONMENT: dev
API_PORT: 3007
COMPASS_API_KEY:
COMPASS_PRE_SHARED_KEY: <used for lookups>
MONITORING_PORT: 3010
USE_DEV_CERTS: false

PAYMASTER_URL: https://rpc.zerodev.app/api/v2/paymaster/your-account-uuid
RPC_URL: https://polygon.gateway.tenderly.co/your-account
BUNDLER_URL: https://rpc.zerodev.app/api/v2/bundler/your-account-uuid
JWT_KEY_SET_URL: https://auth.dimo.zone/keys
CLIENT_ID: 0x51dacC165f1306Abfbf0a6312ec96E13AAA826DB

LOGIN_URL: https://login.dev.dimo.org
DEVICE_DEFINITIONS_API_URL: https://device-definitions-api.dev.dimo.zone
ACCOUNTS_API_URL: https://accounts.dev.dimo.org
ORACLE_API_URL: https://ingest-compass-iot.dev.dimo.zone
IDENTITY_API_URL: https://identity-api.dev.dimo.zone/query

TURNKEY_ORG_ID:
TURNKEY_API_URL:
TURNKEY_RP_ID: dimo.org